markdown: kramdown
permalink: /:year/:month/:title/
url: http://yanran.li
author: 
  name: Yanran Li
  email: yanranli.summer@gmail.com
  
github: niangaotuantuan

pygments: true
paginate: 21
